# Generated by Django 2.1.5 on 2019-02-28 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('likelion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True, max_length=200)),
                ('likelion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likelion.likelion')),
            ],
        ),
    ]
